### ISSUE TITLE
patching bootchain traceback

### ISSUE THREAD

**Issue by m37robertson** [marijuanARM/Inferius#7]
MatthewsMacBook:Inferius matthew$ ./inferius.py -d iPhone6,2 -i 11.3 -f /Users/matthew/Downloads/iPhone_4.0_64bit_11.3_15E216_Restore.ipsw 
Finding Firmware bundle for iPhone6,2, 11.3...
Extracting IPSW. This may take a while, please wait...
IPSW extracted! Verifying bootchain...
Bootchain verified! Patching bootchain...
Traceback (most recent call last):
  File "./inferius.py", line 89, in <module>
    patch.patch_bootchain(firmware_bundle, ipsw_dir, firm_bundle_number)
  File "/Users/matthew/Downloads/Inferius/resources/patch.py", line 21, in patch_bootchain
    bsdiff4.file_patch_inplace(f'work/ipsw/{ibss[0]}', f'{firm_bundle}/{ibss[1]}')
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bsdiff4/format.py", line 104, in file_patch_inplace
    fo.write(core.patch(data, *read_patch(fi)))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bsdiff4/format.py", line 40, in read_patch
    assert magic[:7] == MAGIC[:7]
AssertionError
MatthewsMacBook:Inferius matthew$ 

-----------------------------------------------
have installed the requirements, sorry in advance if this is something simple

**Comment by NotHereForTheDong** [comment]
You need python3 installed

brew install python should fix it

**Comment by m37robertson** [comment]
did your suggestion, same traceback issue
also tried:
python3 inferius.py -d iPhone6,2 -i 11.3 -f /Users/matthew/Downloads/iPhone_4.0_64bit_11.3_15E216_Restore.ipsw

got the same issue still
added a log file incase you need it or anything

thanks

[log.txt](https://github.com/marijuanARM/Inferius/files/5173768/log.txt)

**Comment by m37robertson** [comment]
i looked into it as much as i could and it seems like the some of the bsd patch
files in the FirmwareBundles are invalid. the assertion in bsdiff4 appears to
be generated due to an invalid magic number. i ran the bsd file command over the
patch files and it seems that a few particular patch files are corrupt.

./resources/FirmwareBundles/iPhone6,2_11.3_bundle/kernelcache.release.iphone6.patch
./resources/FirmwareBundles/iPhone6,2_11.3_bundle/iBSS.iphone6.RELEASE.patch
./resources/FirmwareBundles/iPhone6,2_11.3_bundle/iBEC.iphone6.RELEASE.patch
./resources/FirmwareBundles/iPhone6,1_11.3_bundle/kernelcache.release.iphone6.patch
./resources/FirmwareBundles/iPhone6,1_11.3_bundle/iBSS.iphone6.RELEASE.patch
./resources/FirmwareBundles/iPhone6,1_11.3_bundle/iBEC.iphone6.RELEASE.patch

each of these files start with a seemingly erroneous 'ENDSLEY/' signature, as
opposed to the regular BSDIFF4 signature.

using another version (in my case 12.4) instead of 11.3 appears to not throw the
error.

**Comment by NotHereForTheDong** [comment]
I don't know how the patches become corrupted, I just reuploaded them and they now apply.
